### ISSUE TITLE
Wrong precompiled contracts code in 0.3 release

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-contracts#266] opened 2018-09-17 10:41 UTC
I ran into some strange issues when trying to decode `ChannelClosed` events in the status page backend inside docker. After some debugging with @rakanalh we found out that the issue comes from including the old 0.2 release ABI in the precompiled ABI file (`contracts.json.gz`).

We need to:
- [ ] Fix the packaging code to generate the proper ABI for a release
- [ ] See if we can replace the 0.3 package or release a 0.3.1 release with the proper precompiled ABI

**Comment by ulope** [comment] 2018-09-17 11:05
The 0.3.0 release was made manually. That could be the cause for outdated contracts being in there. 

The automated builds performed on travis can’t have that problem.

Still it would be good to improve the packaging code.

Regarding releasing a fixed version: for security purposes it’s impossible to overwrite a release in PyPI. Releasing the fixed version as 0.3.1 should be fine.

**Comment by LefterisJP** [comment] 2018-09-17 11:10
Hmm so we need to release a new package asap then. I woudl be `0.3.1`. Assigning to this milestone.

**Comment by LefterisJP** [comment] 2018-09-17 11:17
So @ulope what's the method of making a release here? I thought that simply bumping the version and doing the python setup.py and sdist upload was supposed to be the only way to make releases here.

**Comment by ulope** [comment] 2018-09-17 11:29
There is automated deployment for travis but it won't work until konrad is back and can fix the account. 

The problem AFAIK is that failure to compile the contracts isn't considered a fatal error (so as not to make the setup.py unusable when people don't have solc installed). 

We could add a similar system as is in raiden for the web ui compilation. There we added a flag (via environment variable) that will make a compile failure raise an exception instead of just printing a message. There we're using that in travis. Here we could for example do so in a Makefile `release` command for example.

**Comment by LefterisJP** [comment] 2018-09-17 11:32
Let's just go with the easiest solution possible. If a release can be made while contracts can't be precompiled that's a big problem and needs to be solved.

**Comment by LefterisJP** [comment] 2018-09-17 11:42
When this is fixed, the solution should also handle https://github.com/raiden-network/raiden/issues/2495

**Comment by pcppcp** [comment] 2018-09-27 15:48
@agatsoh can you provide more context?

**Comment by agatsoh** [comment] 2018-09-27 15:55
I did not have solc installed. But still @palango thinks there might be some deeper issues so i am pasting the output here. https://gist.github.com/agatsoh/7d7f0dca142749100575104a9cb2f03c

**Comment by pcppcp** [comment] 2018-09-27 15:59
hm, first please make sure you have `raiden-contracts` installed from pypi, and not as a local installation

you should have
```
$ pip freeze | grep contracts
raiden-contracts==0.4.0
```

**Comment by agatsoh** [comment] 2018-09-27 16:13
@pcppcp I do have that installed. exactly same.

**Comment by hackaugusto** [comment] 2018-09-27 16:15
Could we please add the version of the smart contracts in the abi json, so that we can check the version of the precompiled abi against the version of the smart contracts deployed in the blockchain?

**Comment by andrevmatos** [comment] 2018-10-01 14:07
Also got it, below goes the traceback including the event which generated the exception. Removing `contracts.json.gz` and letting `solc` generate one on-the-fly fixed it locally:
```
raiden_1  | 2018-10-01 13:33:49 [debug    ] Blockchain event               [raiden.blockchain_events_handler] chain_event=<Event contract: 03c4ab05 event: {'args': AttributeDict({'channel_identifier': 7, 'participant': '0x8f5810964821208bD8271B1323266Ce37f6167E9', 'total_deposit': 6}), 'event': 'ChannelNewDeposit', 'logIndex': 2, 'transactionIndex': 2, 'transactionHash': HexBytes('0x50115a24f579f52324b85c1051c43251c6f7f98fb506aa486ab436189750adfe'), 'address': '0x03c4Ab05f8664fF4E9bACDDe4BbF80831e8eE2fF', 'blockHash': HexBytes('0xe95ec475821243af099953fe9f772f733ad19c0f0b12730fd5541412e0cca4ba'), 'blockNumber': 3972729, 'block_number': 3972729, 'channel_identifier': 7, 'deposit': 6, 'participant': b"\x8fX\x10\x96H! \x8b\xd8'\x1b\x13#&l\xe3\x7fag\xe9"}> contract=03c4ab05 node=008135fa
raiden_1  | Traceback (most recent call last):
raiden_1  |   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
raiden_1  |     "__main__", mod_spec)
raiden_1  |   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
raiden_1  |     exec(code, run_globals)
raiden_1  |   File "/app/raiden/raiden/__main__.py", line 15, in <module>
raiden_1  |     main()
raiden_1  |   File "/app/raiden/raiden/__main__.py", line 11, in main
...
raiden_1  |   File "/app/raiden/raiden/ui/cli.py", line 1192, in run
raiden_1  |     NodeRunner(kwargs, ctx).run()
raiden_1  |   File "/app/raiden/raiden/ui/cli.py", line 1023, in run
raiden_1  |     app = self._run_app()
raiden_1  |   File "/app/raiden/raiden/ui/cli.py", line 1042, in _run_app
raiden_1  |     app_ = run_app(**self._options)
raiden_1  |   File "/app/raiden/raiden/ui/cli.py", line 851, in run_app
raiden_1  |     raiden_app.start()
raiden_1  |   File "/app/raiden/raiden/app.py", line 139, in start
raiden_1  |     self.raiden.start()
raiden_1  |   File "/app/raiden/raiden/raiden_service.py", line 332, in start
raiden_1  |     self.alarm.first_run()
raiden_1  |   File "/app/raiden/raiden/tasks.py", line 175, in first_run
raiden_1  |     self._run_callbacks(latest_block)
raiden_1  |   File "/app/raiden/raiden/tasks.py", line 181, in _run_callbacks
raiden_1  |     result = callback(latest_block)
raiden_1  |   File "/app/raiden/raiden/raiden_service.py", line 514, in _callback_new_block
raiden_1  |     for event in self.blockchain_events.poll_blockchain_events(latest_block_number):
raiden_1  |   File "/app/raiden/raiden/blockchain/events.py", line 232, in poll_blockchain_events
raiden_1  |     log_event,
raiden_1  |   File "/app/raiden/raiden/utils/filters.py", line 93, in decode_event
raiden_1  |     event_abi = topic_to_event_abi[event_id]
raiden_1  | KeyError: HexBytes('0x5fe3d4a343010393184843ef4873386b572e844e89f6b41c9f60f5ab912fbdfe')
```

**Comment by konradkonrad** [comment] 2018-10-05 12:48
According to my research [0], raiden-contracts hasn't had a release with the correct compiled contracts.

```
(raiden-contracts) [konrad@dasneu raiden-contracts]$ git checkout v0.1.0
Previous HEAD position was 089ea63 Bump version: 0.3.1 → 0.4.0
HEAD is now at 585f8a0 Merge pull request #191 from ulope/release_0.1.0
(raiden-contracts) [konrad@dasneu raiden-contracts]$ /tmp/get_checksum.py
Version: 0.1.0
source checksum: 846d3b4768180022556038a8811a2e0d93284e2a63637db7569567f97453624b
released checksum: 203ea8c23f4c80c5f353453c220a366f0df43acaef7f4864bee6af285ab6853e
matching: False
precompiled exists in source: False
(raiden-contracts) [konrad@dasneu raiden-contracts]$ git checkout v0.2.0
Previous HEAD position was 585f8a0 Merge pull request #191 from ulope/release_0.1.0
HEAD is now at 1aeed27 Bump version: 0.1.0 → 0.2.0
(raiden-contracts) [konrad@dasneu raiden-contracts]$ /tmp/get_checksum.py
Version: 0.2.0
source checksum: 61ff3dd7ecc590b3931bf7ab1b92c1e8ff77491ffcf7095954f2892839e7954e
released checksum: 3b2c9e430a771f09051b7095d114d9819476cacad896ecbe12dc71f7a07d6476
matching: False
precompiled exists in source: False
(raiden-contracts) [konrad@dasneu raiden-contracts]$ git checkout v0.3.0
Previous HEAD position was 1aeed27 Bump version: 0.1.0 → 0.2.0
HEAD is now at 4a228e0 Merge pull request #257 from LefterisJP/bump_to_v0.3.0
(raiden-contracts) [konrad@dasneu raiden-contracts]$ /tmp/get_checksum.py
Version: 0.3.0
source checksum: a52c01153e3c14545d66c52934c4b4f5cfe027ee3dbc3a11c871594e20d10989
released checksum: 3b2c9e430a771f09051b7095d114d9819476cacad896ecbe12dc71f7a07d6476
matching: False
precompiled exists in source: False
(raiden-contracts) [konrad@dasneu raiden-contracts]$ git checkout v0.3.1
Previous HEAD position was 4a228e0 Merge pull request #257 from LefterisJP/bump_to_v0.3.0
HEAD is now at 7105cf8 Bump version: 0.3.0 → 0.3.1
(raiden-contracts) [konrad@dasneu raiden-contracts]$ /tmp/get_checksum.py
Version: 0.3.1
source checksum: a52c01153e3c14545d66c52934c4b4f5cfe027ee3dbc3a11c871594e20d10989
released checksum: ca1facf8e61aa39e6687497a99cdd9df09b6b7d2705d561372cde2d9f99f7951
matching: False
precompiled exists in source: False
(raiden-contracts) [konrad@dasneu raiden-contracts]$ git checkout v0.4.0
Previous HEAD position was 7105cf8 Bump version: 0.3.0 → 0.3.1
HEAD is now at 089ea63 Bump version: 0.3.1 → 0.4.0
(raiden-contracts) [konrad@dasneu raiden-contracts]$ /tmp/get_checksum.py
Version: 0.4.0
source checksum: f0831aca947b2b4e842eca0b650399e3f30a2d564f3455678ece404f2bffa196
released checksum: 3b2c9e430a771f09051b7095d114d9819476cacad896ecbe12dc71f7a07d6476
matching: False
precompiled exists in source: False
```

[0] The tool for the above output is located at https://gist.github.com/konradkonrad/8210826dd685f4a0df2f79d8c1645fdb

Since #295 is merged, I assume, we can close this ticket.

**Closed by konradkonrad** 2018-10-05 12:48 UTC
